[package]
name = "check-lockfile-intersection"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-lock = "9.0.0"
attohttpc = "0.16.0"
url = "2.5.0"
